# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_control.ui'
#
# Created: Tue Apr  1 12:58:28 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(894, 808)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.gateLedDigitalControlTab = QtGui.QWidget()
        self.gateLedDigitalControlTab.setObjectName(_fromUtf8("gateLedDigitalControlTab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.gateLedDigitalControlTab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.digitalControlsGroupBox = QtGui.QGroupBox(self.gateLedDigitalControlTab)
        self.digitalControlsGroupBox.setAutoFillBackground(False)
        self.digitalControlsGroupBox.setObjectName(_fromUtf8("digitalControlsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.digitalControlsGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.digitalGatesGroupBox = QtGui.QGroupBox(self.digitalControlsGroupBox)
        self.digitalGatesGroupBox.setObjectName(_fromUtf8("digitalGatesGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.digitalGatesGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gateOpenCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.gateOpenCheckBox.setEnabled(False)
        self.gateOpenCheckBox.setChecked(True)
        self.gateOpenCheckBox.setObjectName(_fromUtf8("gateOpenCheckBox"))
        self.horizontalLayout.addWidget(self.gateOpenCheckBox)
        self.gateCloseCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.gateCloseCheckBox.setEnabled(False)
        self.gateCloseCheckBox.setObjectName(_fromUtf8("gateCloseCheckBox"))
        self.horizontalLayout.addWidget(self.gateCloseCheckBox)
        self.line_43 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_43.setEnabled(False)
        self.line_43.setFrameShape(QtGui.QFrame.VLine)
        self.line_43.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_43.setObjectName(_fromUtf8("line_43"))
        self.horizontalLayout.addWidget(self.line_43)
        self.gateOpenLabel = QtGui.QLabel(self.digitalGatesGroupBox)
        self.gateOpenLabel.setEnabled(False)
        self.gateOpenLabel.setObjectName(_fromUtf8("gateOpenLabel"))
        self.horizontalLayout.addWidget(self.gateOpenLabel)
        self.gateOpenValueLabel = QtGui.QLabel(self.digitalGatesGroupBox)
        self.gateOpenValueLabel.setEnabled(False)
        self.gateOpenValueLabel.setText(_fromUtf8(""))
        self.gateOpenValueLabel.setObjectName(_fromUtf8("gateOpenValueLabel"))
        self.horizontalLayout.addWidget(self.gateOpenValueLabel)
        self.line_44 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_44.setEnabled(False)
        self.line_44.setFrameShape(QtGui.QFrame.VLine)
        self.line_44.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_44.setObjectName(_fromUtf8("line_44"))
        self.horizontalLayout.addWidget(self.line_44)
        self.gateCloseLabel = QtGui.QLabel(self.digitalGatesGroupBox)
        self.gateCloseLabel.setEnabled(False)
        self.gateCloseLabel.setObjectName(_fromUtf8("gateCloseLabel"))
        self.horizontalLayout.addWidget(self.gateCloseLabel)
        self.gateCloseValueLabel = QtGui.QLabel(self.digitalGatesGroupBox)
        self.gateCloseValueLabel.setEnabled(False)
        self.gateCloseValueLabel.setText(_fromUtf8(""))
        self.gateCloseValueLabel.setObjectName(_fromUtf8("gateCloseValueLabel"))
        self.horizontalLayout.addWidget(self.gateCloseValueLabel)
        self.line_45 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_45.setEnabled(False)
        self.line_45.setFrameShape(QtGui.QFrame.VLine)
        self.line_45.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_45.setObjectName(_fromUtf8("line_45"))
        self.horizontalLayout.addWidget(self.line_45)
        self.digitalServoAngleDegreesLabel = QtGui.QLabel(self.digitalGatesGroupBox)
        self.digitalServoAngleDegreesLabel.setEnabled(False)
        self.digitalServoAngleDegreesLabel.setObjectName(_fromUtf8("digitalServoAngleDegreesLabel"))
        self.horizontalLayout.addWidget(self.digitalServoAngleDegreesLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.line_3 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.line_5 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 6, 5, 1, 1)
        self.line = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 6, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 6, 3, 1, 1)
        self.tagaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.tagaCheckBox.setObjectName(_fromUtf8("tagaCheckBox"))
        self.gridLayout.addWidget(self.tagaCheckBox, 1, 0, 1, 1)
        self.line_12 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout.addWidget(self.line_12, 6, 1, 1, 1)
        self.t4g0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t4g0CheckBox.setText(_fromUtf8(""))
        self.t4g0CheckBox.setObjectName(_fromUtf8("t4g0CheckBox"))
        self.gridLayout.addWidget(self.t4g0CheckBox, 5, 6, 1, 1)
        self.t5g1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t5g1CheckBox.setText(_fromUtf8(""))
        self.t5g1CheckBox.setObjectName(_fromUtf8("t5g1CheckBox"))
        self.gridLayout.addWidget(self.t5g1CheckBox, 4, 7, 1, 1)
        self.line_4 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 6, 4, 1, 1)
        self.tag2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.tag2CheckBox.setObjectName(_fromUtf8("tag2CheckBox"))
        self.gridLayout.addWidget(self.tag2CheckBox, 3, 0, 1, 1)
        self.line_11 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout.addWidget(self.line_11, 5, 1, 1, 1)
        self.t4g1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t4g1CheckBox.setText(_fromUtf8(""))
        self.t4g1CheckBox.setObjectName(_fromUtf8("t4g1CheckBox"))
        self.gridLayout.addWidget(self.t4g1CheckBox, 4, 6, 1, 1)
        self.t0g0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t0g0CheckBox.setText(_fromUtf8(""))
        self.t0g0CheckBox.setObjectName(_fromUtf8("t0g0CheckBox"))
        self.gridLayout.addWidget(self.t0g0CheckBox, 5, 2, 1, 1)
        self.t0gaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t0gaCheckBox.setObjectName(_fromUtf8("t0gaCheckBox"))
        self.gridLayout.addWidget(self.t0gaCheckBox, 1, 2, 1, 1)
        self.t0g1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t0g1CheckBox.setText(_fromUtf8(""))
        self.t0g1CheckBox.setObjectName(_fromUtf8("t0g1CheckBox"))
        self.gridLayout.addWidget(self.t0g1CheckBox, 4, 2, 1, 1)
        self.t5g2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t5g2CheckBox.setText(_fromUtf8(""))
        self.t5g2CheckBox.setObjectName(_fromUtf8("t5g2CheckBox"))
        self.gridLayout.addWidget(self.t5g2CheckBox, 3, 7, 1, 1)
        self.line_9 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout.addWidget(self.line_9, 3, 1, 1, 1)
        self.t3g2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t3g2CheckBox.setText(_fromUtf8(""))
        self.t3g2CheckBox.setObjectName(_fromUtf8("t3g2CheckBox"))
        self.gridLayout.addWidget(self.t3g2CheckBox, 3, 5, 1, 1)
        self.t2g0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t2g0CheckBox.setText(_fromUtf8(""))
        self.t2g0CheckBox.setObjectName(_fromUtf8("t2g0CheckBox"))
        self.gridLayout.addWidget(self.t2g0CheckBox, 5, 4, 1, 1)
        self.t3g0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t3g0CheckBox.setText(_fromUtf8(""))
        self.t3g0CheckBox.setObjectName(_fromUtf8("t3g0CheckBox"))
        self.gridLayout.addWidget(self.t3g0CheckBox, 5, 5, 1, 1)
        self.line_10 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout.addWidget(self.line_10, 4, 1, 1, 1)
        self.t3g1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t3g1CheckBox.setText(_fromUtf8(""))
        self.t3g1CheckBox.setObjectName(_fromUtf8("t3g1CheckBox"))
        self.gridLayout.addWidget(self.t3g1CheckBox, 4, 5, 1, 1)
        self.t3gaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t3gaCheckBox.setObjectName(_fromUtf8("t3gaCheckBox"))
        self.gridLayout.addWidget(self.t3gaCheckBox, 1, 5, 1, 1)
        self.tag1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.tag1CheckBox.setObjectName(_fromUtf8("tag1CheckBox"))
        self.gridLayout.addWidget(self.tag1CheckBox, 4, 0, 1, 1)
        self.tag0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.tag0CheckBox.setObjectName(_fromUtf8("tag0CheckBox"))
        self.gridLayout.addWidget(self.tag0CheckBox, 5, 0, 1, 1)
        self.t1gaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t1gaCheckBox.setObjectName(_fromUtf8("t1gaCheckBox"))
        self.gridLayout.addWidget(self.t1gaCheckBox, 1, 3, 1, 1)
        self.t4g2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t4g2CheckBox.setText(_fromUtf8(""))
        self.t4g2CheckBox.setObjectName(_fromUtf8("t4g2CheckBox"))
        self.gridLayout.addWidget(self.t4g2CheckBox, 3, 6, 1, 1)
        self.t0g2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t0g2CheckBox.setText(_fromUtf8(""))
        self.t0g2CheckBox.setObjectName(_fromUtf8("t0g2CheckBox"))
        self.gridLayout.addWidget(self.t0g2CheckBox, 3, 2, 1, 1)
        self.t1g1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t1g1CheckBox.setText(_fromUtf8(""))
        self.t1g1CheckBox.setObjectName(_fromUtf8("t1g1CheckBox"))
        self.gridLayout.addWidget(self.t1g1CheckBox, 4, 3, 1, 1)
        self.t5gaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t5gaCheckBox.setObjectName(_fromUtf8("t5gaCheckBox"))
        self.gridLayout.addWidget(self.t5gaCheckBox, 1, 7, 1, 1)
        self.line_8 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout.addWidget(self.line_8, 1, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout.addWidget(self.line_7, 6, 7, 1, 1)
        self.t2g1CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t2g1CheckBox.setText(_fromUtf8(""))
        self.t2g1CheckBox.setObjectName(_fromUtf8("t2g1CheckBox"))
        self.gridLayout.addWidget(self.t2g1CheckBox, 4, 4, 1, 1)
        self.t1g0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t1g0CheckBox.setText(_fromUtf8(""))
        self.t1g0CheckBox.setObjectName(_fromUtf8("t1g0CheckBox"))
        self.gridLayout.addWidget(self.t1g0CheckBox, 5, 3, 1, 1)
        self.line_6 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 6, 6, 1, 1)
        self.t2g2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t2g2CheckBox.setText(_fromUtf8(""))
        self.t2g2CheckBox.setObjectName(_fromUtf8("t2g2CheckBox"))
        self.gridLayout.addWidget(self.t2g2CheckBox, 3, 4, 1, 1)
        self.t5g0CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t5g0CheckBox.setText(_fromUtf8(""))
        self.t5g0CheckBox.setObjectName(_fromUtf8("t5g0CheckBox"))
        self.gridLayout.addWidget(self.t5g0CheckBox, 5, 7, 1, 1)
        self.line_14 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout.addWidget(self.line_14, 2, 2, 1, 1)
        self.line_15 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout.addWidget(self.line_15, 2, 3, 1, 1)
        self.line_16 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout.addWidget(self.line_16, 2, 4, 1, 1)
        self.line_17 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout.addWidget(self.line_17, 2, 5, 1, 1)
        self.line_18 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout.addWidget(self.line_18, 2, 6, 1, 1)
        self.line_19 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout.addWidget(self.line_19, 2, 7, 1, 1)
        self.t1g2CheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t1g2CheckBox.setText(_fromUtf8(""))
        self.t1g2CheckBox.setObjectName(_fromUtf8("t1g2CheckBox"))
        self.gridLayout.addWidget(self.t1g2CheckBox, 3, 3, 1, 1)
        self.line_20 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout.addWidget(self.line_20, 2, 0, 1, 1)
        self.line_25 = QtGui.QFrame(self.digitalGatesGroupBox)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.gridLayout.addWidget(self.line_25, 2, 1, 1, 1)
        self.t2gaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t2gaCheckBox.setObjectName(_fromUtf8("t2gaCheckBox"))
        self.gridLayout.addWidget(self.t2gaCheckBox, 1, 4, 1, 1)
        self.t4gaCheckBox = QtGui.QCheckBox(self.digitalGatesGroupBox)
        self.t4gaCheckBox.setObjectName(_fromUtf8("t4gaCheckBox"))
        self.gridLayout.addWidget(self.t4gaCheckBox, 1, 6, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.digitalGatesGroupBox)
        self.digitalLedsGroupBox = QtGui.QGroupBox(self.digitalControlsGroupBox)
        self.digitalLedsGroupBox.setObjectName(_fromUtf8("digitalLedsGroupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.digitalLedsGroupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.ledOnCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.ledOnCheckBox.setEnabled(False)
        self.ledOnCheckBox.setChecked(True)
        self.ledOnCheckBox.setObjectName(_fromUtf8("ledOnCheckBox"))
        self.horizontalLayout_3.addWidget(self.ledOnCheckBox)
        self.ledOffCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.ledOffCheckBox.setEnabled(False)
        self.ledOffCheckBox.setObjectName(_fromUtf8("ledOffCheckBox"))
        self.horizontalLayout_3.addWidget(self.ledOffCheckBox)
        self.line_40 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_40.setEnabled(False)
        self.line_40.setFrameShape(QtGui.QFrame.VLine)
        self.line_40.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_40.setObjectName(_fromUtf8("line_40"))
        self.horizontalLayout_3.addWidget(self.line_40)
        self.ledOnLabel = QtGui.QLabel(self.digitalLedsGroupBox)
        self.ledOnLabel.setEnabled(False)
        self.ledOnLabel.setObjectName(_fromUtf8("ledOnLabel"))
        self.horizontalLayout_3.addWidget(self.ledOnLabel)
        self.ledOnValueLabel = QtGui.QLabel(self.digitalLedsGroupBox)
        self.ledOnValueLabel.setEnabled(False)
        self.ledOnValueLabel.setText(_fromUtf8(""))
        self.ledOnValueLabel.setObjectName(_fromUtf8("ledOnValueLabel"))
        self.horizontalLayout_3.addWidget(self.ledOnValueLabel)
        self.line_41 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_41.setEnabled(False)
        self.line_41.setFrameShape(QtGui.QFrame.VLine)
        self.line_41.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_41.setObjectName(_fromUtf8("line_41"))
        self.horizontalLayout_3.addWidget(self.line_41)
        self.ledOffLabel = QtGui.QLabel(self.digitalLedsGroupBox)
        self.ledOffLabel.setEnabled(False)
        self.ledOffLabel.setObjectName(_fromUtf8("ledOffLabel"))
        self.horizontalLayout_3.addWidget(self.ledOffLabel)
        self.ledOffValueLabel = QtGui.QLabel(self.digitalLedsGroupBox)
        self.ledOffValueLabel.setEnabled(False)
        self.ledOffValueLabel.setText(_fromUtf8(""))
        self.ledOffValueLabel.setObjectName(_fromUtf8("ledOffValueLabel"))
        self.horizontalLayout_3.addWidget(self.ledOffValueLabel)
        self.line_42 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_42.setEnabled(False)
        self.line_42.setFrameShape(QtGui.QFrame.VLine)
        self.line_42.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_42.setObjectName(_fromUtf8("line_42"))
        self.horizontalLayout_3.addWidget(self.line_42)
        self.digitalDutyCycleLabel = QtGui.QLabel(self.digitalLedsGroupBox)
        self.digitalDutyCycleLabel.setEnabled(False)
        self.digitalDutyCycleLabel.setObjectName(_fromUtf8("digitalDutyCycleLabel"))
        self.horizontalLayout_3.addWidget(self.digitalDutyCycleLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.t1l0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t1l0CheckBox.setText(_fromUtf8(""))
        self.t1l0CheckBox.setObjectName(_fromUtf8("t1l0CheckBox"))
        self.gridLayout_2.addWidget(self.t1l0CheckBox, 2, 8, 1, 1)
        self.t3laCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t3laCheckBox.setObjectName(_fromUtf8("t3laCheckBox"))
        self.gridLayout_2.addWidget(self.t3laCheckBox, 0, 10, 1, 1)
        self.t3l1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t3l1CheckBox.setEnabled(False)
        self.t3l1CheckBox.setText(_fromUtf8(""))
        self.t3l1CheckBox.setObjectName(_fromUtf8("t3l1CheckBox"))
        self.gridLayout_2.addWidget(self.t3l1CheckBox, 3, 10, 1, 1)
        self.t0l1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t0l1CheckBox.setEnabled(False)
        self.t0l1CheckBox.setText(_fromUtf8(""))
        self.t0l1CheckBox.setObjectName(_fromUtf8("t0l1CheckBox"))
        self.gridLayout_2.addWidget(self.t0l1CheckBox, 3, 7, 1, 1)
        self.line_32 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_32.setFrameShape(QtGui.QFrame.HLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.gridLayout_2.addWidget(self.line_32, 4, 7, 1, 1)
        self.t2l0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t2l0CheckBox.setText(_fromUtf8(""))
        self.t2l0CheckBox.setObjectName(_fromUtf8("t2l0CheckBox"))
        self.gridLayout_2.addWidget(self.t2l0CheckBox, 2, 9, 1, 1)
        self.line_28 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_28.setFrameShape(QtGui.QFrame.HLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.gridLayout_2.addWidget(self.line_28, 1, 10, 1, 1)
        self.line_30 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_30.setFrameShape(QtGui.QFrame.HLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.gridLayout_2.addWidget(self.line_30, 1, 12, 1, 1)
        self.t2l1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t2l1CheckBox.setEnabled(False)
        self.t2l1CheckBox.setText(_fromUtf8(""))
        self.t2l1CheckBox.setObjectName(_fromUtf8("t2l1CheckBox"))
        self.gridLayout_2.addWidget(self.t2l1CheckBox, 3, 9, 1, 1)
        self.t3l0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t3l0CheckBox.setText(_fromUtf8(""))
        self.t3l0CheckBox.setObjectName(_fromUtf8("t3l0CheckBox"))
        self.gridLayout_2.addWidget(self.t3l0CheckBox, 2, 10, 1, 1)
        self.t0laCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t0laCheckBox.setObjectName(_fromUtf8("t0laCheckBox"))
        self.gridLayout_2.addWidget(self.t0laCheckBox, 0, 7, 1, 1)
        self.t1l1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t1l1CheckBox.setEnabled(False)
        self.t1l1CheckBox.setText(_fromUtf8(""))
        self.t1l1CheckBox.setObjectName(_fromUtf8("t1l1CheckBox"))
        self.gridLayout_2.addWidget(self.t1l1CheckBox, 3, 8, 1, 1)
        self.t4l0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t4l0CheckBox.setText(_fromUtf8(""))
        self.t4l0CheckBox.setObjectName(_fromUtf8("t4l0CheckBox"))
        self.gridLayout_2.addWidget(self.t4l0CheckBox, 2, 11, 1, 1)
        self.t5l1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t5l1CheckBox.setEnabled(False)
        self.t5l1CheckBox.setText(_fromUtf8(""))
        self.t5l1CheckBox.setObjectName(_fromUtf8("t5l1CheckBox"))
        self.gridLayout_2.addWidget(self.t5l1CheckBox, 3, 12, 1, 1)
        self.t5l0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t5l0CheckBox.setText(_fromUtf8(""))
        self.t5l0CheckBox.setObjectName(_fromUtf8("t5l0CheckBox"))
        self.gridLayout_2.addWidget(self.t5l0CheckBox, 2, 12, 1, 1)
        self.t4l1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t4l1CheckBox.setEnabled(False)
        self.t4l1CheckBox.setText(_fromUtf8(""))
        self.t4l1CheckBox.setObjectName(_fromUtf8("t4l1CheckBox"))
        self.gridLayout_2.addWidget(self.t4l1CheckBox, 3, 11, 1, 1)
        self.tal1CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.tal1CheckBox.setEnabled(False)
        self.tal1CheckBox.setObjectName(_fromUtf8("tal1CheckBox"))
        self.gridLayout_2.addWidget(self.tal1CheckBox, 3, 5, 1, 1)
        self.tal0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.tal0CheckBox.setObjectName(_fromUtf8("tal0CheckBox"))
        self.gridLayout_2.addWidget(self.tal0CheckBox, 2, 5, 1, 1)
        self.t1laCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t1laCheckBox.setObjectName(_fromUtf8("t1laCheckBox"))
        self.gridLayout_2.addWidget(self.t1laCheckBox, 0, 8, 1, 1)
        self.t5laCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t5laCheckBox.setObjectName(_fromUtf8("t5laCheckBox"))
        self.gridLayout_2.addWidget(self.t5laCheckBox, 0, 12, 1, 1)
        self.t4laCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t4laCheckBox.setObjectName(_fromUtf8("t4laCheckBox"))
        self.gridLayout_2.addWidget(self.t4laCheckBox, 0, 11, 1, 1)
        self.t2laCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t2laCheckBox.setObjectName(_fromUtf8("t2laCheckBox"))
        self.gridLayout_2.addWidget(self.t2laCheckBox, 0, 9, 1, 1)
        self.t0l0CheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.t0l0CheckBox.setText(_fromUtf8(""))
        self.t0l0CheckBox.setObjectName(_fromUtf8("t0l0CheckBox"))
        self.gridLayout_2.addWidget(self.t0l0CheckBox, 2, 7, 1, 1)
        self.line_27 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_27.setFrameShape(QtGui.QFrame.HLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.gridLayout_2.addWidget(self.line_27, 1, 9, 1, 1)
        self.line_22 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.gridLayout_2.addWidget(self.line_22, 4, 10, 1, 1)
        self.line_29 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_29.setFrameShape(QtGui.QFrame.HLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.gridLayout_2.addWidget(self.line_29, 1, 11, 1, 1)
        self.line_26 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.gridLayout_2.addWidget(self.line_26, 1, 8, 1, 1)
        self.line_24 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.gridLayout_2.addWidget(self.line_24, 1, 7, 1, 1)
        self.line_31 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_31.setFrameShape(QtGui.QFrame.HLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.gridLayout_2.addWidget(self.line_31, 4, 5, 1, 1)
        self.line_33 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_33.setFrameShape(QtGui.QFrame.HLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.gridLayout_2.addWidget(self.line_33, 4, 11, 1, 1)
        self.line_34 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_34.setFrameShape(QtGui.QFrame.HLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.gridLayout_2.addWidget(self.line_34, 4, 12, 1, 1)
        self.line_21 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_2.addWidget(self.line_21, 4, 9, 1, 1)
        self.talaCheckBox = QtGui.QCheckBox(self.digitalLedsGroupBox)
        self.talaCheckBox.setObjectName(_fromUtf8("talaCheckBox"))
        self.gridLayout_2.addWidget(self.talaCheckBox, 0, 5, 1, 1)
        self.line_23 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.gridLayout_2.addWidget(self.line_23, 1, 5, 1, 1)
        self.line_13 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_2.addWidget(self.line_13, 4, 8, 1, 1)
        self.line_35 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_35.setFrameShape(QtGui.QFrame.VLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.gridLayout_2.addWidget(self.line_35, 0, 6, 1, 1)
        self.line_36 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_36.setFrameShape(QtGui.QFrame.VLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.gridLayout_2.addWidget(self.line_36, 2, 6, 1, 1)
        self.line_37 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_37.setFrameShape(QtGui.QFrame.VLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.gridLayout_2.addWidget(self.line_37, 3, 6, 1, 1)
        self.line_38 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_38.setFrameShape(QtGui.QFrame.HLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.gridLayout_2.addWidget(self.line_38, 1, 6, 1, 1)
        self.line_39 = QtGui.QFrame(self.digitalLedsGroupBox)
        self.line_39.setFrameShape(QtGui.QFrame.HLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.gridLayout_2.addWidget(self.line_39, 4, 6, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.digitalLedsGroupBox)
        self.verticalLayout_8.addWidget(self.digitalControlsGroupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.tabWidget.addTab(self.gateLedDigitalControlTab, _fromUtf8(""))
        self.gateLedAnalogControlTab = QtGui.QWidget()
        self.gateLedAnalogControlTab.setEnabled(True)
        self.gateLedAnalogControlTab.setObjectName(_fromUtf8("gateLedAnalogControlTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gateLedAnalogControlTab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.analogControlsGroupBox = QtGui.QGroupBox(self.gateLedAnalogControlTab)
        self.analogControlsGroupBox.setEnabled(True)
        self.analogControlsGroupBox.setCheckable(False)
        self.analogControlsGroupBox.setChecked(False)
        self.analogControlsGroupBox.setObjectName(_fromUtf8("analogControlsGroupBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.analogControlsGroupBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.analogGatesGroupBox = QtGui.QGroupBox(self.analogControlsGroupBox)
        self.analogGatesGroupBox.setEnabled(True)
        self.analogGatesGroupBox.setObjectName(_fromUtf8("analogGatesGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.analogGatesGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.analogGateLabel = QtGui.QLabel(self.analogGatesGroupBox)
        self.analogGateLabel.setObjectName(_fromUtf8("analogGateLabel"))
        self.gridLayout_3.addWidget(self.analogGateLabel, 1, 1, 1, 1)
        self.analogGateTunnelLabel = QtGui.QLabel(self.analogGatesGroupBox)
        self.analogGateTunnelLabel.setObjectName(_fromUtf8("analogGateTunnelLabel"))
        self.gridLayout_3.addWidget(self.analogGateTunnelLabel, 0, 1, 1, 1)
        self.analogGateSpinBox = QtGui.QSpinBox(self.analogGatesGroupBox)
        self.analogGateSpinBox.setMinimum(20)
        self.analogGateSpinBox.setMaximum(165)
        self.analogGateSpinBox.setObjectName(_fromUtf8("analogGateSpinBox"))
        self.gridLayout_3.addWidget(self.analogGateSpinBox, 1, 4, 1, 1)
        self.analogGateComboBox = QtGui.QComboBox(self.analogGatesGroupBox)
        self.analogGateComboBox.setObjectName(_fromUtf8("analogGateComboBox"))
        self.analogGateComboBox.addItem(_fromUtf8(""))
        self.analogGateComboBox.addItem(_fromUtf8(""))
        self.analogGateComboBox.addItem(_fromUtf8(""))
        self.analogGateComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.analogGateComboBox, 1, 2, 1, 1)
        self.analogServoAngleDegreesLabel = QtGui.QLabel(self.analogGatesGroupBox)
        self.analogServoAngleDegreesLabel.setObjectName(_fromUtf8("analogServoAngleDegreesLabel"))
        self.gridLayout_3.addWidget(self.analogServoAngleDegreesLabel, 0, 4, 1, 1)
        self.analogGateTunnelComboBox = QtGui.QComboBox(self.analogGatesGroupBox)
        self.analogGateTunnelComboBox.setObjectName(_fromUtf8("analogGateTunnelComboBox"))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.analogGateTunnelComboBox.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.analogGateTunnelComboBox, 0, 2, 1, 1)
        self.analogGateOpenPushButton = QtGui.QPushButton(self.analogGatesGroupBox)
        self.analogGateOpenPushButton.setObjectName(_fromUtf8("analogGateOpenPushButton"))
        self.gridLayout_3.addWidget(self.analogGateOpenPushButton, 0, 5, 1, 1)
        self.analogGateClosePushButton = QtGui.QPushButton(self.analogGatesGroupBox)
        self.analogGateClosePushButton.setObjectName(_fromUtf8("analogGateClosePushButton"))
        self.gridLayout_3.addWidget(self.analogGateClosePushButton, 1, 5, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gateCloseLabel_2 = QtGui.QLabel(self.analogGatesGroupBox)
        self.gateCloseLabel_2.setObjectName(_fromUtf8("gateCloseLabel_2"))
        self.gridLayout_6.addWidget(self.gateCloseLabel_2, 1, 0, 1, 1)
        self.gateOpenLabel_2 = QtGui.QLabel(self.analogGatesGroupBox)
        self.gateOpenLabel_2.setObjectName(_fromUtf8("gateOpenLabel_2"))
        self.gridLayout_6.addWidget(self.gateOpenLabel_2, 0, 0, 1, 1)
        self.gateCloseValueLabel_2 = QtGui.QLabel(self.analogGatesGroupBox)
        self.gateCloseValueLabel_2.setText(_fromUtf8(""))
        self.gateCloseValueLabel_2.setObjectName(_fromUtf8("gateCloseValueLabel_2"))
        self.gridLayout_6.addWidget(self.gateCloseValueLabel_2, 1, 1, 1, 1)
        self.gateOpenValueLabel_2 = QtGui.QLabel(self.analogGatesGroupBox)
        self.gateOpenValueLabel_2.setText(_fromUtf8(""))
        self.gateOpenValueLabel_2.setObjectName(_fromUtf8("gateOpenValueLabel_2"))
        self.gridLayout_6.addWidget(self.gateOpenValueLabel_2, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 0, 3, 1, 1)
        self.analogGateHorizontalSlider = QtGui.QSlider(self.analogGatesGroupBox)
        self.analogGateHorizontalSlider.setMinimum(20)
        self.analogGateHorizontalSlider.setMaximum(165)
        self.analogGateHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.analogGateHorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.analogGateHorizontalSlider.setTickInterval(5)
        self.analogGateHorizontalSlider.setObjectName(_fromUtf8("analogGateHorizontalSlider"))
        self.gridLayout_3.addWidget(self.analogGateHorizontalSlider, 1, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.analogGatesGroupBox)
        self.analogLedsGroupBox = QtGui.QGroupBox(self.analogControlsGroupBox)
        self.analogLedsGroupBox.setEnabled(True)
        self.analogLedsGroupBox.setObjectName(_fromUtf8("analogLedsGroupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.analogLedsGroupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.analogDutyCycleLabel = QtGui.QLabel(self.analogLedsGroupBox)
        self.analogDutyCycleLabel.setObjectName(_fromUtf8("analogDutyCycleLabel"))
        self.gridLayout_4.addWidget(self.analogDutyCycleLabel, 1, 4, 1, 1)
        self.analogLedTunnelLabel = QtGui.QLabel(self.analogLedsGroupBox)
        self.analogLedTunnelLabel.setObjectName(_fromUtf8("analogLedTunnelLabel"))
        self.gridLayout_4.addWidget(self.analogLedTunnelLabel, 1, 1, 1, 1)
        self.analogLedComboBox = QtGui.QComboBox(self.analogLedsGroupBox)
        self.analogLedComboBox.setEditable(False)
        self.analogLedComboBox.setObjectName(_fromUtf8("analogLedComboBox"))
        self.analogLedComboBox.addItem(_fromUtf8(""))
        self.analogLedComboBox.addItem(_fromUtf8(""))
        self.analogLedComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.analogLedComboBox, 2, 2, 1, 1)
        self.analogLedTunnelComboBox = QtGui.QComboBox(self.analogLedsGroupBox)
        self.analogLedTunnelComboBox.setEditable(False)
        self.analogLedTunnelComboBox.setObjectName(_fromUtf8("analogLedTunnelComboBox"))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.analogLedTunnelComboBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.analogLedTunnelComboBox, 1, 2, 1, 1)
        self.analogLedHorizontalSlider = QtGui.QSlider(self.analogLedsGroupBox)
        self.analogLedHorizontalSlider.setMaximum(100)
        self.analogLedHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.analogLedHorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.analogLedHorizontalSlider.setTickInterval(10)
        self.analogLedHorizontalSlider.setObjectName(_fromUtf8("analogLedHorizontalSlider"))
        self.gridLayout_4.addWidget(self.analogLedHorizontalSlider, 2, 3, 1, 1)
        self.analogLedOnPushButton = QtGui.QPushButton(self.analogLedsGroupBox)
        self.analogLedOnPushButton.setObjectName(_fromUtf8("analogLedOnPushButton"))
        self.gridLayout_4.addWidget(self.analogLedOnPushButton, 2, 5, 1, 1)
        self.analogLedSpinBox = QtGui.QSpinBox(self.analogLedsGroupBox)
        self.analogLedSpinBox.setEnabled(True)
        self.analogLedSpinBox.setFrame(True)
        self.analogLedSpinBox.setReadOnly(False)
        self.analogLedSpinBox.setMaximum(100)
        self.analogLedSpinBox.setObjectName(_fromUtf8("analogLedSpinBox"))
        self.gridLayout_4.addWidget(self.analogLedSpinBox, 2, 4, 1, 1)
        self.analogLedLabel = QtGui.QLabel(self.analogLedsGroupBox)
        self.analogLedLabel.setObjectName(_fromUtf8("analogLedLabel"))
        self.gridLayout_4.addWidget(self.analogLedLabel, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.ledOnLabel_2 = QtGui.QLabel(self.analogLedsGroupBox)
        self.ledOnLabel_2.setObjectName(_fromUtf8("ledOnLabel_2"))
        self.horizontalLayout_5.addWidget(self.ledOnLabel_2)
        self.ledOnValueLabel_2 = QtGui.QLabel(self.analogLedsGroupBox)
        self.ledOnValueLabel_2.setText(_fromUtf8(""))
        self.ledOnValueLabel_2.setObjectName(_fromUtf8("ledOnValueLabel_2"))
        self.horizontalLayout_5.addWidget(self.ledOnValueLabel_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 3, 1, 1)
        self.verticalLayout_9.addWidget(self.analogLedsGroupBox)
        self.verticalLayout_3.addWidget(self.analogControlsGroupBox)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.tabWidget.addTab(self.gateLedAnalogControlTab, _fromUtf8(""))
        self.olfactometersControlTab = QtGui.QWidget()
        self.olfactometersControlTab.setObjectName(_fromUtf8("olfactometersControlTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.olfactometersControlTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.olfactometersControlTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ethanolOffPushButton = QtGui.QPushButton(self.groupBox)
        self.ethanolOffPushButton.setObjectName(_fromUtf8("ethanolOffPushButton"))
        self.horizontalLayout_2.addWidget(self.ethanolOffPushButton)
        self.ethanolValve0RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve0RadioButton.setObjectName(_fromUtf8("ethanolValve0RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve0RadioButton)
        self.ethanolValve1RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve1RadioButton.setObjectName(_fromUtf8("ethanolValve1RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve1RadioButton)
        self.ethanolValve2RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve2RadioButton.setObjectName(_fromUtf8("ethanolValve2RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve2RadioButton)
        self.ethanolValve3RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve3RadioButton.setObjectName(_fromUtf8("ethanolValve3RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve3RadioButton)
        self.ethanolValve4RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve4RadioButton.setObjectName(_fromUtf8("ethanolValve4RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve4RadioButton)
        self.ethanolValve5RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve5RadioButton.setObjectName(_fromUtf8("ethanolValve5RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve5RadioButton)
        self.ethanolValve6RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve6RadioButton.setObjectName(_fromUtf8("ethanolValve6RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve6RadioButton)
        self.ethanolValve7RadioButton = QtGui.QRadioButton(self.groupBox)
        self.ethanolValve7RadioButton.setObjectName(_fromUtf8("ethanolValve7RadioButton"))
        self.horizontalLayout_2.addWidget(self.ethanolValve7RadioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ethanolMfc0Label = QtGui.QLabel(self.groupBox)
        self.ethanolMfc0Label.setObjectName(_fromUtf8("ethanolMfc0Label"))
        self.horizontalLayout_6.addWidget(self.ethanolMfc0Label)
        self.ethanolMfc0HorizontalSlider = QtGui.QSlider(self.groupBox)
        self.ethanolMfc0HorizontalSlider.setMaximum(100)
        self.ethanolMfc0HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ethanolMfc0HorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.ethanolMfc0HorizontalSlider.setTickInterval(10)
        self.ethanolMfc0HorizontalSlider.setObjectName(_fromUtf8("ethanolMfc0HorizontalSlider"))
        self.horizontalLayout_6.addWidget(self.ethanolMfc0HorizontalSlider)
        self.ethanolMfc0ValueLabel = QtGui.QLabel(self.groupBox)
        self.ethanolMfc0ValueLabel.setText(_fromUtf8(""))
        self.ethanolMfc0ValueLabel.setObjectName(_fromUtf8("ethanolMfc0ValueLabel"))
        self.horizontalLayout_6.addWidget(self.ethanolMfc0ValueLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.ethanolMfc1Label = QtGui.QLabel(self.groupBox)
        self.ethanolMfc1Label.setObjectName(_fromUtf8("ethanolMfc1Label"))
        self.horizontalLayout_7.addWidget(self.ethanolMfc1Label)
        self.ethanolMfc1HorizontalSlider = QtGui.QSlider(self.groupBox)
        self.ethanolMfc1HorizontalSlider.setMaximum(100)
        self.ethanolMfc1HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ethanolMfc1HorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.ethanolMfc1HorizontalSlider.setTickInterval(10)
        self.ethanolMfc1HorizontalSlider.setObjectName(_fromUtf8("ethanolMfc1HorizontalSlider"))
        self.horizontalLayout_7.addWidget(self.ethanolMfc1HorizontalSlider)
        self.ethanolMfc1ValueLabel = QtGui.QLabel(self.groupBox)
        self.ethanolMfc1ValueLabel.setText(_fromUtf8(""))
        self.ethanolMfc1ValueLabel.setObjectName(_fromUtf8("ethanolMfc1ValueLabel"))
        self.horizontalLayout_7.addWidget(self.ethanolMfc1ValueLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.olfactometersControlTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.odor1OffPushButton = QtGui.QPushButton(self.groupBox_2)
        self.odor1OffPushButton.setObjectName(_fromUtf8("odor1OffPushButton"))
        self.horizontalLayout_8.addWidget(self.odor1OffPushButton)
        self.odor1Valve0RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve0RadioButton.setObjectName(_fromUtf8("odor1Valve0RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve0RadioButton)
        self.odor1Valve1RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve1RadioButton.setObjectName(_fromUtf8("odor1Valve1RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve1RadioButton)
        self.odor1Valve2RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve2RadioButton.setObjectName(_fromUtf8("odor1Valve2RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve2RadioButton)
        self.odor1Valve3RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve3RadioButton.setObjectName(_fromUtf8("odor1Valve3RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve3RadioButton)
        self.odor1Valve4RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve4RadioButton.setObjectName(_fromUtf8("odor1Valve4RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve4RadioButton)
        self.odor1Valve5RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve5RadioButton.setObjectName(_fromUtf8("odor1Valve5RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve5RadioButton)
        self.odor1Valve6RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve6RadioButton.setObjectName(_fromUtf8("odor1Valve6RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve6RadioButton)
        self.odor1Valve7RadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.odor1Valve7RadioButton.setObjectName(_fromUtf8("odor1Valve7RadioButton"))
        self.horizontalLayout_8.addWidget(self.odor1Valve7RadioButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.odor1Mfc0Label = QtGui.QLabel(self.groupBox_2)
        self.odor1Mfc0Label.setObjectName(_fromUtf8("odor1Mfc0Label"))
        self.horizontalLayout_9.addWidget(self.odor1Mfc0Label)
        self.odor1Mfc0HorizontalSlider = QtGui.QSlider(self.groupBox_2)
        self.odor1Mfc0HorizontalSlider.setMaximum(100)
        self.odor1Mfc0HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.odor1Mfc0HorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.odor1Mfc0HorizontalSlider.setTickInterval(10)
        self.odor1Mfc0HorizontalSlider.setObjectName(_fromUtf8("odor1Mfc0HorizontalSlider"))
        self.horizontalLayout_9.addWidget(self.odor1Mfc0HorizontalSlider)
        self.odor1Mfc0ValueLabel = QtGui.QLabel(self.groupBox_2)
        self.odor1Mfc0ValueLabel.setText(_fromUtf8(""))
        self.odor1Mfc0ValueLabel.setObjectName(_fromUtf8("odor1Mfc0ValueLabel"))
        self.horizontalLayout_9.addWidget(self.odor1Mfc0ValueLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.odor1Mfc1Label = QtGui.QLabel(self.groupBox_2)
        self.odor1Mfc1Label.setObjectName(_fromUtf8("odor1Mfc1Label"))
        self.horizontalLayout_10.addWidget(self.odor1Mfc1Label)
        self.odor1Mfc1HorizontalSlider = QtGui.QSlider(self.groupBox_2)
        self.odor1Mfc1HorizontalSlider.setMaximum(100)
        self.odor1Mfc1HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.odor1Mfc1HorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.odor1Mfc1HorizontalSlider.setTickInterval(10)
        self.odor1Mfc1HorizontalSlider.setObjectName(_fromUtf8("odor1Mfc1HorizontalSlider"))
        self.horizontalLayout_10.addWidget(self.odor1Mfc1HorizontalSlider)
        self.odor1Mfc1ValueLabel = QtGui.QLabel(self.groupBox_2)
        self.odor1Mfc1ValueLabel.setText(_fromUtf8(""))
        self.odor1Mfc1ValueLabel.setObjectName(_fromUtf8("odor1Mfc1ValueLabel"))
        self.horizontalLayout_10.addWidget(self.odor1Mfc1ValueLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.olfactometersControlTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.odor0OffPushButton = QtGui.QPushButton(self.groupBox_3)
        self.odor0OffPushButton.setObjectName(_fromUtf8("odor0OffPushButton"))
        self.horizontalLayout_11.addWidget(self.odor0OffPushButton)
        self.odor0Valve0RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve0RadioButton.setObjectName(_fromUtf8("odor0Valve0RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve0RadioButton)
        self.odor0Valve1RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve1RadioButton.setObjectName(_fromUtf8("odor0Valve1RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve1RadioButton)
        self.odor0Valve2RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve2RadioButton.setObjectName(_fromUtf8("odor0Valve2RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve2RadioButton)
        self.odor0Valve3RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve3RadioButton.setObjectName(_fromUtf8("odor0Valve3RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve3RadioButton)
        self.odor0Valve4RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve4RadioButton.setObjectName(_fromUtf8("odor0Valve4RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve4RadioButton)
        self.odor0Valve5RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve5RadioButton.setObjectName(_fromUtf8("odor0Valve5RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve5RadioButton)
        self.odor0Valve6RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve6RadioButton.setObjectName(_fromUtf8("odor0Valve6RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve6RadioButton)
        self.odor0Valve7RadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.odor0Valve7RadioButton.setObjectName(_fromUtf8("odor0Valve7RadioButton"))
        self.horizontalLayout_11.addWidget(self.odor0Valve7RadioButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.odor0Mfc0Label = QtGui.QLabel(self.groupBox_3)
        self.odor0Mfc0Label.setObjectName(_fromUtf8("odor0Mfc0Label"))
        self.horizontalLayout_12.addWidget(self.odor0Mfc0Label)
        self.odor0Mfc0HorizontalSlider = QtGui.QSlider(self.groupBox_3)
        self.odor0Mfc0HorizontalSlider.setMaximum(100)
        self.odor0Mfc0HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.odor0Mfc0HorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.odor0Mfc0HorizontalSlider.setTickInterval(10)
        self.odor0Mfc0HorizontalSlider.setObjectName(_fromUtf8("odor0Mfc0HorizontalSlider"))
        self.horizontalLayout_12.addWidget(self.odor0Mfc0HorizontalSlider)
        self.odor0Mfc0ValueLabel = QtGui.QLabel(self.groupBox_3)
        self.odor0Mfc0ValueLabel.setText(_fromUtf8(""))
        self.odor0Mfc0ValueLabel.setObjectName(_fromUtf8("odor0Mfc0ValueLabel"))
        self.horizontalLayout_12.addWidget(self.odor0Mfc0ValueLabel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.odor0Mfc1Label = QtGui.QLabel(self.groupBox_3)
        self.odor0Mfc1Label.setObjectName(_fromUtf8("odor0Mfc1Label"))
        self.horizontalLayout_13.addWidget(self.odor0Mfc1Label)
        self.odor0Mfc1HorizontalSlider = QtGui.QSlider(self.groupBox_3)
        self.odor0Mfc1HorizontalSlider.setMaximum(100)
        self.odor0Mfc1HorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.odor0Mfc1HorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.odor0Mfc1HorizontalSlider.setTickInterval(10)
        self.odor0Mfc1HorizontalSlider.setObjectName(_fromUtf8("odor0Mfc1HorizontalSlider"))
        self.horizontalLayout_13.addWidget(self.odor0Mfc1HorizontalSlider)
        self.odor0Mfc1ValueLabel = QtGui.QLabel(self.groupBox_3)
        self.odor0Mfc1ValueLabel.setText(_fromUtf8(""))
        self.odor0Mfc1ValueLabel.setObjectName(_fromUtf8("odor0Mfc1ValueLabel"))
        self.horizontalLayout_13.addWidget(self.odor0Mfc1ValueLabel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.olfactometersControlTab, _fromUtf8(""))
        self.highCurrentLedControlTab = QtGui.QWidget()
        self.highCurrentLedControlTab.setObjectName(_fromUtf8("highCurrentLedControlTab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.highCurrentLedControlTab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.startPwmPushButton = QtGui.QPushButton(self.highCurrentLedControlTab)
        self.startPwmPushButton.setObjectName(_fromUtf8("startPwmPushButton"))
        self.horizontalLayout_17.addWidget(self.startPwmPushButton)
        self.stopPwmPushButton = QtGui.QPushButton(self.highCurrentLedControlTab)
        self.stopPwmPushButton.setObjectName(_fromUtf8("stopPwmPushButton"))
        self.horizontalLayout_17.addWidget(self.stopPwmPushButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label = QtGui.QLabel(self.highCurrentLedControlTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_14.addWidget(self.label)
        self.percentCapacityHorizontalSlider = QtGui.QSlider(self.highCurrentLedControlTab)
        self.percentCapacityHorizontalSlider.setMinimum(10)
        self.percentCapacityHorizontalSlider.setMaximum(100)
        self.percentCapacityHorizontalSlider.setSingleStep(10)
        self.percentCapacityHorizontalSlider.setPageStep(20)
        self.percentCapacityHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.percentCapacityHorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.percentCapacityHorizontalSlider.setTickInterval(10)
        self.percentCapacityHorizontalSlider.setObjectName(_fromUtf8("percentCapacityHorizontalSlider"))
        self.horizontalLayout_14.addWidget(self.percentCapacityHorizontalSlider)
        self.percentCapacityLabel = QtGui.QLabel(self.highCurrentLedControlTab)
        self.percentCapacityLabel.setText(_fromUtf8(""))
        self.percentCapacityLabel.setObjectName(_fromUtf8("percentCapacityLabel"))
        self.horizontalLayout_14.addWidget(self.percentCapacityLabel)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_3 = QtGui.QLabel(self.highCurrentLedControlTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        self.durationOnHorizontalSlider = QtGui.QSlider(self.highCurrentLedControlTab)
        self.durationOnHorizontalSlider.setMinimum(100)
        self.durationOnHorizontalSlider.setMaximum(5000)
        self.durationOnHorizontalSlider.setSingleStep(100)
        self.durationOnHorizontalSlider.setPageStep(1000)
        self.durationOnHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.durationOnHorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.durationOnHorizontalSlider.setTickInterval(1000)
        self.durationOnHorizontalSlider.setObjectName(_fromUtf8("durationOnHorizontalSlider"))
        self.horizontalLayout_15.addWidget(self.durationOnHorizontalSlider)
        self.durationOnLabel = QtGui.QLabel(self.highCurrentLedControlTab)
        self.durationOnLabel.setText(_fromUtf8(""))
        self.durationOnLabel.setObjectName(_fromUtf8("durationOnLabel"))
        self.horizontalLayout_15.addWidget(self.durationOnLabel)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_5 = QtGui.QLabel(self.highCurrentLedControlTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_16.addWidget(self.label_5)
        self.durationOffHorizontalSlider = QtGui.QSlider(self.highCurrentLedControlTab)
        self.durationOffHorizontalSlider.setMinimum(100)
        self.durationOffHorizontalSlider.setMaximum(5000)
        self.durationOffHorizontalSlider.setSingleStep(100)
        self.durationOffHorizontalSlider.setPageStep(1000)
        self.durationOffHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.durationOffHorizontalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.durationOffHorizontalSlider.setTickInterval(1000)
        self.durationOffHorizontalSlider.setObjectName(_fromUtf8("durationOffHorizontalSlider"))
        self.horizontalLayout_16.addWidget(self.durationOffHorizontalSlider)
        self.durationOffLabel = QtGui.QLabel(self.highCurrentLedControlTab)
        self.durationOffLabel.setText(_fromUtf8(""))
        self.durationOffLabel.setObjectName(_fromUtf8("durationOffLabel"))
        self.horizontalLayout_16.addWidget(self.durationOffLabel)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.highCurrentLedControlTab, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionUsage = QtGui.QAction(MainWindow)
        self.actionUsage.setObjectName(_fromUtf8("actionUsage"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Fly Alcohol Assay Manual Control GUI v0.1.1", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalControlsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Digital Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalGatesGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Gates", None, QtGui.QApplication.UnicodeUTF8))
        self.gateOpenCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Gate Open", None, QtGui.QApplication.UnicodeUTF8))
        self.gateCloseCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Gate Close", None, QtGui.QApplication.UnicodeUTF8))
        self.gateOpenLabel.setText(QtGui.QApplication.translate("MainWindow", "Open Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.gateCloseLabel.setText(QtGui.QApplication.translate("MainWindow", "Close Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalServoAngleDegreesLabel.setText(QtGui.QApplication.translate("MainWindow", "Servo Angle Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.tagaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "All Gates", None, QtGui.QApplication.UnicodeUTF8))
        self.tag2CheckBox.setText(QtGui.QApplication.translate("MainWindow", "Gate 3", None, QtGui.QApplication.UnicodeUTF8))
        self.t0gaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.t3gaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 4", None, QtGui.QApplication.UnicodeUTF8))
        self.tag1CheckBox.setText(QtGui.QApplication.translate("MainWindow", "Gate 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tag0CheckBox.setText(QtGui.QApplication.translate("MainWindow", "Gate 1", None, QtGui.QApplication.UnicodeUTF8))
        self.t1gaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.t5gaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 6", None, QtGui.QApplication.UnicodeUTF8))
        self.t2gaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 3", None, QtGui.QApplication.UnicodeUTF8))
        self.t4gaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 5", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalLedsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Leds", None, QtGui.QApplication.UnicodeUTF8))
        self.ledOnCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Led On", None, QtGui.QApplication.UnicodeUTF8))
        self.ledOffCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Led Off", None, QtGui.QApplication.UnicodeUTF8))
        self.ledOnLabel.setText(QtGui.QApplication.translate("MainWindow", "On Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.ledOffLabel.setText(QtGui.QApplication.translate("MainWindow", "Off Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.digitalDutyCycleLabel.setText(QtGui.QApplication.translate("MainWindow", "Duty Cycle %", None, QtGui.QApplication.UnicodeUTF8))
        self.t3laCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 4", None, QtGui.QApplication.UnicodeUTF8))
        self.t0laCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tal1CheckBox.setText(QtGui.QApplication.translate("MainWindow", "Led 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tal0CheckBox.setText(QtGui.QApplication.translate("MainWindow", "Led 1", None, QtGui.QApplication.UnicodeUTF8))
        self.t1laCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 2", None, QtGui.QApplication.UnicodeUTF8))
        self.t5laCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 6", None, QtGui.QApplication.UnicodeUTF8))
        self.t4laCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 5", None, QtGui.QApplication.UnicodeUTF8))
        self.t2laCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tunnel 3", None, QtGui.QApplication.UnicodeUTF8))
        self.talaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "All Leds", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gateLedDigitalControlTab), QtGui.QApplication.translate("MainWindow", "Gate and Led Digital Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.analogControlsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Analog Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGatesGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Gates", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateLabel.setText(QtGui.QApplication.translate("MainWindow", "Gate", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelLabel.setText(QtGui.QApplication.translate("MainWindow", "Tunnel", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.analogServoAngleDegreesLabel.setText(QtGui.QApplication.translate("MainWindow", "Servo Angle Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateTunnelComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateOpenPushButton.setText(QtGui.QApplication.translate("MainWindow", "Set \"Open\" to This Value", None, QtGui.QApplication.UnicodeUTF8))
        self.analogGateClosePushButton.setText(QtGui.QApplication.translate("MainWindow", "Set \"Close\" to This Value", None, QtGui.QApplication.UnicodeUTF8))
        self.gateCloseLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Close Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.gateOpenLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Open Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Leds", None, QtGui.QApplication.UnicodeUTF8))
        self.analogDutyCycleLabel.setText(QtGui.QApplication.translate("MainWindow", "Duty Cycle %", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelLabel.setText(QtGui.QApplication.translate("MainWindow", "Tunnel", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedTunnelComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedOnPushButton.setText(QtGui.QApplication.translate("MainWindow", "Set \"On\" to This Value", None, QtGui.QApplication.UnicodeUTF8))
        self.analogLedLabel.setText(QtGui.QApplication.translate("MainWindow", "Led", None, QtGui.QApplication.UnicodeUTF8))
        self.ledOnLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Led On Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gateLedAnalogControlTab), QtGui.QApplication.translate("MainWindow", "Gate and Led Analog Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Ethanol Olfactometer", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolOffPushButton.setText(QtGui.QApplication.translate("MainWindow", "All Valves Off", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve0RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Dummy", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve1RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve2RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 2", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve3RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 3", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve4RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 4", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve5RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 5", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve6RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 6", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolValve7RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 7", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolMfc0Label.setText(QtGui.QApplication.translate("MainWindow", "MFC 1", None, QtGui.QApplication.UnicodeUTF8))
        self.ethanolMfc1Label.setText(QtGui.QApplication.translate("MainWindow", "MFC 2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Odor 2 Olfactometer", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1OffPushButton.setText(QtGui.QApplication.translate("MainWindow", "All Valves Off", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve0RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Dummy", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve1RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 1", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve2RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 2", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve3RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 3", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve4RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 4", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve5RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 5", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve6RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 6", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Valve7RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 7", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Mfc0Label.setText(QtGui.QApplication.translate("MainWindow", "MFC 1", None, QtGui.QApplication.UnicodeUTF8))
        self.odor1Mfc1Label.setText(QtGui.QApplication.translate("MainWindow", "MFC 2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Odor 1 Olfactometer", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0OffPushButton.setText(QtGui.QApplication.translate("MainWindow", "All Valves Off", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve0RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Dummy", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve1RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 1", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve2RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 2", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve3RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 3", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve4RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 4", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve5RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 5", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve6RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 6", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Valve7RadioButton.setText(QtGui.QApplication.translate("MainWindow", "Valve 7", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Mfc0Label.setText(QtGui.QApplication.translate("MainWindow", "MFC 1", None, QtGui.QApplication.UnicodeUTF8))
        self.odor0Mfc1Label.setText(QtGui.QApplication.translate("MainWindow", "MFC 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.olfactometersControlTab), QtGui.QApplication.translate("MainWindow", "Olfactometer Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.startPwmPushButton.setText(QtGui.QApplication.translate("MainWindow", "Start PWM", None, QtGui.QApplication.UnicodeUTF8))
        self.stopPwmPushButton.setText(QtGui.QApplication.translate("MainWindow", "Stop PWM", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "% Capacity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Duration On (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Duration Off (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.highCurrentLedControlTab), QtGui.QApplication.translate("MainWindow", "High Current Led Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUsage.setText(QtGui.QApplication.translate("MainWindow", "Usage", None, QtGui.QApplication.UnicodeUTF8))

